/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/$not-found'
import { Route as TaxiIndexImport } from './routes/taxi/index'
import { Route as PokemonIndexImport } from './routes/pokemon/index'
import { Route as HotelIndexImport } from './routes/hotel/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardPlaygroundIndexImport } from './routes/dashboard/playground/index'
import { Route as DashboardPlaygroundHistoryImport } from './routes/dashboard/playground/history'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  id: '/$not-found',
  path: '/$not-found',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TaxiIndexRoute = TaxiIndexImport.update({
  id: '/taxi/',
  path: '/taxi/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIndexRoute = PokemonIndexImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRoute,
} as any)

const HotelIndexRoute = HotelIndexImport.update({
  id: '/hotel/',
  path: '/hotel/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardPlaygroundIndexRoute = DashboardPlaygroundIndexImport.update({
  id: '/dashboard/playground/',
  path: '/dashboard/playground/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardPlaygroundHistoryRoute = DashboardPlaygroundHistoryImport.update(
  {
    id: '/dashboard/playground/history',
    path: '/dashboard/playground/history',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$not-found': {
      id: '/$not-found'
      path: '/$not-found'
      fullPath: '/$not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/hotel/': {
      id: '/hotel/'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelIndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonIndexImport
      parentRoute: typeof rootRoute
    }
    '/taxi/': {
      id: '/taxi/'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/playground/history': {
      id: '/dashboard/playground/history'
      path: '/dashboard/playground/history'
      fullPath: '/dashboard/playground/history'
      preLoaderRoute: typeof DashboardPlaygroundHistoryImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/playground/': {
      id: '/dashboard/playground/'
      path: '/dashboard/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$not-found': typeof NotFoundRoute
  '/dashboard': typeof DashboardIndexRoute
  '/hotel': typeof HotelIndexRoute
  '/pokemon': typeof PokemonIndexRoute
  '/taxi': typeof TaxiIndexRoute
  '/dashboard/playground/history': typeof DashboardPlaygroundHistoryRoute
  '/dashboard/playground': typeof DashboardPlaygroundIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$not-found': typeof NotFoundRoute
  '/dashboard': typeof DashboardIndexRoute
  '/hotel': typeof HotelIndexRoute
  '/pokemon': typeof PokemonIndexRoute
  '/taxi': typeof TaxiIndexRoute
  '/dashboard/playground/history': typeof DashboardPlaygroundHistoryRoute
  '/dashboard/playground': typeof DashboardPlaygroundIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$not-found': typeof NotFoundRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hotel/': typeof HotelIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/taxi/': typeof TaxiIndexRoute
  '/dashboard/playground/history': typeof DashboardPlaygroundHistoryRoute
  '/dashboard/playground/': typeof DashboardPlaygroundIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$not-found'
    | '/dashboard'
    | '/hotel'
    | '/pokemon'
    | '/taxi'
    | '/dashboard/playground/history'
    | '/dashboard/playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$not-found'
    | '/dashboard'
    | '/hotel'
    | '/pokemon'
    | '/taxi'
    | '/dashboard/playground/history'
    | '/dashboard/playground'
  id:
    | '__root__'
    | '/'
    | '/$not-found'
    | '/dashboard/'
    | '/hotel/'
    | '/pokemon/'
    | '/taxi/'
    | '/dashboard/playground/history'
    | '/dashboard/playground/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  NotFoundRoute: typeof NotFoundRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  HotelIndexRoute: typeof HotelIndexRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
  TaxiIndexRoute: typeof TaxiIndexRoute
  DashboardPlaygroundHistoryRoute: typeof DashboardPlaygroundHistoryRoute
  DashboardPlaygroundIndexRoute: typeof DashboardPlaygroundIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NotFoundRoute: NotFoundRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HotelIndexRoute: HotelIndexRoute,
  PokemonIndexRoute: PokemonIndexRoute,
  TaxiIndexRoute: TaxiIndexRoute,
  DashboardPlaygroundHistoryRoute: DashboardPlaygroundHistoryRoute,
  DashboardPlaygroundIndexRoute: DashboardPlaygroundIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$not-found",
        "/dashboard/",
        "/hotel/",
        "/pokemon/",
        "/taxi/",
        "/dashboard/playground/history",
        "/dashboard/playground/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$not-found": {
      "filePath": "$not-found.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/hotel/": {
      "filePath": "hotel/index.tsx"
    },
    "/pokemon/": {
      "filePath": "pokemon/index.tsx"
    },
    "/taxi/": {
      "filePath": "taxi/index.tsx"
    },
    "/dashboard/playground/history": {
      "filePath": "dashboard/playground/history.tsx"
    },
    "/dashboard/playground/": {
      "filePath": "dashboard/playground/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
